
var xhr = require('utils/xhr');

module.exports = {
    getStoryLists: function(options,callback){
        xhr.simpleCall({
            func:'storyLists',
            query:options
        },function(res){
            callback(res.result);
        });
    },
    getCommentLists:function(options,callback){
         xhr.simpleCall({
            func:'storyComments',
            data:options,
        },function(res){
            callback(res.result);
        });
    },
    getBossTalk:function(options,callback){
         xhr.simpleCall({
            func:'storyBossTalk',
            query:options
        },function(res){
            callback(res.result);
        });
    },
    setPlayerCounter:function(data,callback){
         xhr.simpleCall({
            method:'POST',
            func:'storyPlayerCounter',
            data:JSON.stringify(data)
            
        },function(res){
            callback(res);
        });
    },
    setCmtComment:function(data,callback){
        xhr.simpleCall({
            method:'POST',
            func:'storyCmtWrite',
            data:JSON.stringify(data),
            contentType:'application/json',
        },function(res){
            callback(res);
        });
    },
    setCmtPraise:function(data,callback){
        xhr.simpleCall({
            func:'storyCmtPraise',
            data:JSON.stringify(data),
            method:'POST'
        },function(res){
            callback(res);
        });
    },
    setCmtCancelPraise:function(data,callback){
        xhr.simpleCall({
            func:'storyCmtCancelPraise',
            data:JSON.stringify(data),
            method:'POST'
        },function(res){
            callback(res);
        });
    },
    getStorysByIds:function(data,callback){
        xhr.simpleCall({
            func:'storyDetailByIds',
            data:JSON.stringify(data),
            method:'POST'
        },function(res){
            callback(res.result);
        });
    },
    getStoryListByAlbumId:function(options,callback){
        xhr.simpleCall({
            func:'storyListByalbumId',
            query:options
        },function(res){
            callback(res.result);
        });
    },
     getplayPageBannerList:function(options,callback){
        xhr.simpleCall({
            func:'playPageBannerList',
            query:options
        },function(res){
            callback(res.result);
        });
    }
};